name: Production Build

on:
  push:
    tags:
      - v*

jobs:
  build_ios_production:
    type: build
    params:
      platform: ios
      profile: production

  build_ios_preview:
    type: build
    params:
      platform: ios
      profile: preview
